CiscoUCSServerDescription Class Reference
CiscoUCSServerDescription (ie CiscoUCS-012-123:0) breaks out the uniqueness number and port index from the WWPN of a UCS-served physical host.
Public Member Functions
CiscoUCSServerDescription (String wwn)
create an instance with brief set to false.
CiscoUCSServerDescription (boolean brief, String wwn)
create an instance with the given WWN.
String descPort ()
describe the WWPN's unique port label/index
String toString ()
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
CiscoUCSServerDescription (ie CiscoUCS-012-123:0) breaks out the uniqueness number and port index from the WWPN of a UCS-served physical host.
I do tend to see 20000025b5hhhfnnn such that:
hhh is a three-digit host index
f is either 0 or 1 based on fabric A or B
nnn is a three-digit server index
The thing to remember about UCS is that the WWPN are entirely user-defined, are are UUIDs, so this is merely a convention. It might fall apart on the next user!
Definition at line 16 of file CiscoUCSServerDescription.java.
Constructor & Destructor Documentation
CiscoUCSServerDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 19 of file CiscoUCSServerDescription.java.
Referenced by CiscoUCSServerDescription.getDesc().
CiscoUCSServerDescription (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 55 of file CiscoUCSServerDescription.java.
Member Function Documentation
String descPort () [inline]
describe the WWPN's unique port label/index
Returns
the unique name for the port WWPN
Definition at line 88 of file CiscoUCSServerDescription.java.
References WWNDesc.wwn.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong used to restrict matching to strong-matches only. This is a weak-confidence description, so will return null for strong-only matching
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 32 of file CiscoUCSServerDescription.java.
References DevRole.max.
Referenced by WWNDescription.getWWNDescriptor().
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong used to restrict matching to strong-matches only. This is a weak-confidence description, so will return null for strong-only matching
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 40 of file CiscoUCSServerDescription.java.
References CiscoUCSServerDescription.CiscoUCSServerDescription(), and WWNDesc.WWNDescSwitch.isA().
String toString () [inline]
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
See also
getDesc(boolean,boolean,String)
Returns
generated alias or nickname for the WWN
Definition at line 66 of file CiscoUCSServerDescription.java.
References WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/CiscoUCSServerDescription.java