IBM3700Description Class Reference
IBM3700Description (ie RamSan-G8332-FC-2B) breaks out the serial and port information from the Texas Memory Systems hardware initially called RamSan.
Public Member Functions
IBM3700Description (String wwn)
create an instance with brief set to false.
IBM3700Description (boolean brief, String wwn)
create an instance with the given WWN.
String toString ()
return a description or alias for this WWN
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
IBM3700Description (ie RamSan-G8332-FC-2B) breaks out the serial and port information from the Texas Memory Systems hardware initially called RamSan.
Definition at line 13 of file IBM3700Description.java.
Constructor & Destructor Documentation
IBM3700Description (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 16 of file IBM3700Description.java.
Referenced by IBM3700Description.getDesc().
IBM3700Description (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 21 of file IBM3700Description.java.
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is ignored: this class has only one representation of the WWN description or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 34 of file IBM3700Description.java.
References IBM3700Description.IBM3700Description().
Referenced by WWNDescription.getWWNDescriptor().
String toString () [inline]
return a description or alias for this WWN
Returns
generated alias or nickname for the WWN
Definition at line 47 of file IBM3700Description.java.
The documentation for this class was generated from the following file:
java/IBM3700Description.java