HDSModularDescription Class Reference
HDSModularDescription (ie HDS-D850-31787-CTL0-PortD) breaks out the model type, serial, and FA port from the WWPN.
Public Member Functions
HDSModularDescription (String wwn)
create an instance with brief set to false.
HDSModularDescription (boolean brief, String wwn)
create an instance with the given WWN.
String toString ()
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
HDSModularDescription (ie HDS-D850-31787-CTL0-PortD) breaks out the model type, serial, and FA port from the WWPN.
Definition at line 14 of file HDSModularDescription.java.
Constructor & Destructor Documentation
HDSModularDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 17 of file HDSModularDescription.java.
Referenced by HDSModularDescription.getDesc().
HDSModularDescription (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 22 of file HDSModularDescription.java.
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
This function should correspond to HDSVSPDescription::getDesc(boolean, boolean, String) as both are redundant copies simply to avoid an error ustream being leaked out to the user
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 38 of file HDSModularDescription.java.
References DevRole.max.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
This function should correspond to HDSVSPDescription::getDesc(boolean, boolean, String) as both are redundant copies simply to avoid an error ustream being leaked out to the user
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 46 of file HDSModularDescription.java.
References HDSModularDescription.HDSModularDescription(), and WWNDesc.WWNDescTarget.isA().
String toString () [inline]
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
See also
getDesc(boolean,boolean,String)
Returns
generated alias or nickname for the WWN
010 TOM: HDS KA15062: breaks it up as N OOOOOO FFF S ssss P (N=5, OOOOOO = OUI, FFF = Family (010) ssss=Serial % 0x10000, P=Port (0-F) need to check against http://p2v.it/tools/wwndec/index.php?input=50060e8010139322 need to check http://p2v.it/tools/wwndec/index.php?input=50060e8010139322
Definition at line 65 of file HDSModularDescription.java.
References WWNDesc.brief, and WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/HDSModularDescription.java