EMCVPLEXDescription Class Reference
Public Member Functions
EMCVPLEXDescription (String wwn)
create an instance with this.brief set to false.
EMCVPLEXDescription (boolean brief, String wwn)
create an instance with the given WWN.
String toString ()
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Detailed Description
Definition at line 10 of file EMCVPLEXDescription.java.
Constructor & Destructor Documentation
EMCVPLEXDescription (String wwn) [inline]
create an instance with this.brief set to false.
This is a convenience function to support the older constructor model
Parameters
wwn the WWN to evaluate and describe
Definition at line 13 of file EMCVPLEXDescription.java.
Referenced by EMCVPLEXDescription.getDesc().
EMCVPLEXDescription (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 18 of file EMCVPLEXDescription.java.
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 31 of file EMCVPLEXDescription.java.
References EMCVPLEXDescription.EMCVPLEXDescription().
Referenced by WWNDescription.getWWNDescriptor().
String toString () [inline]
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
See Also
getDesc(boolean,boolean,String)
Returns
generated alias or nickname for the WWN
Definition at line 46 of file EMCVPLEXDescription.java.
The documentation for this class was generated from the following file:
java/EMCVPLEXDescription.java