WWNDesc.WWNDescTarget Class Reference
simple pass-thru class to define internal value for a Target in an idempotent way
Public Member Functions
WWNDescTarget (String wwn)
create an instance with brief set to false.
WWNDescTarget (boolean brief, String wwn)
create an instance with the given WWN.
Static Public Member Functions
static boolean isA (int role)
convenience function to use bit-masks to check for membership in this role
Additional Inherited Members
Detailed Description
simple pass-thru class to define internal value for a Target in an idempotent way
Definition at line 139 of file WWNDesc.java.
Constructor & Destructor Documentation
WWNDescTarget (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
< create a new Target device without brief naming capability
Definition at line 142 of file WWNDesc.java.
References DevRole.TARGET.
WWNDescTarget (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
< create a new Target device with given brief capability
Definition at line 147 of file WWNDesc.java.
References DevRole.TARGET.
Member Function Documentation
static boolean isA (int role) [inline], [static]
convenience function to use bit-masks to check for membership in this role
Parameters
role the role to check
Returns
true if the given role includes Switch
< lightweight method to check for membership in this role
Definition at line 158 of file WWNDesc.java.
Referenced by PureStorageDescription.getDesc(), OraclePillarDescription.getDesc(), HPDotHillDescription.getDesc(), EMCClariionDescription.getDesc(), EMCSymmetrixDescription.getDesc(), EMCVPLEXDescription.getDesc(), IBM3700Description.getDesc(), EMCVMAXDescription.getDesc(), IBMSVCDescription.getDesc(), HP3ParDescription.getDesc(), HDSVSPDescription.getDesc(), NetAppDescription.getDesc(), IBMDescription.getDesc(), SymbiosDescription.getDesc(), HDSModularDescription.getDesc(), and IBM500507630Description.getDesc().
The documentation for this class was generated from the following file:
java/WWNDesc.java