HPVirtualServerDescription Class Reference
HPVirtualServerDescription (ie HP-123456:010) breaks out the uniqueness number and port index from the WWPN.
Public Member Functions
HPVirtualServerDescription (String wwn)
create an instance with brief set to false.
HPVirtualServerDescription (boolean brief, String wwn)
create an instance with the given WWN.
String descPort ()
describe the WWPN's unique port label/index
String toString ()
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
HPVirtualServerDescription (ie HP-123456:010) breaks out the uniqueness number and port index from the WWPN.
This one is fairly weak in that HP clearly indicates the 00110a OUI is the unwashed-masses of roll-your-own-WWPN, and users do indeed roll random values. This class is intended more to provide guidance to the uniqueness of a 2nnn00110axxxxxx device wherein for consistent xxxxxx values, nnn does change.
http://h20628.www2.hp.com/km-ext/kmcsdirect/emr_na-c03169041-2.pdf http://h20000.www2.hp.com/bc/docs/support/SupportManual/c03314921/c03314921.pdf.
http://h20000.www2.hp.com/bc/docs/support/SupportManual/c02494590/c02494590.pdf. 50:01:43:80:02:A3:00:00 - 50:01:43:80:02:A4:FF:FF VCEM 50:06:0B:00:00:C2:62:00 - 50:06:0B:00:00:C3:61:FF HP Pre-defined (64 blocks of 1024 IDs: ie C2:62:00 - C2:65:FF
http://www.filibeto.org/unix/hp-ux/lib/os/vpar/6.0/vpars-6.0-npiv-4AA3-8665ENW.pdf The range that HP has reserved for NPIV is 0x50014c2000000000 to 0x50014c27ffffffff for Port WWNs and 0x50014c2800000000 to 0x50014c2fffffffff for Node WWNs. ... When manually configuring vHBAs, vWWNs may safely be picked from the range 0x100000110a0300 - 0x100000110a030fff
http://h20000.www2.hp.com/bc/docs/support/SupportManual/c03967142/c03967142.pdf 10:00:38:9d:30:60:00:00 - 10:00:38:9d:30:6f:ff:ff used in examples of API
50060b00 range used in http://www.filibeto.org/unix/hp-ux/lib/os/vpar/6.0/vpars-6.0-npiv-4AA3-8665ENW.pdf as a config example. Customers tend to follow examples.
00:60:B0 Integrity and HP9000 00:11:0a Compaq Proliant (500110a in servers) 00:01:FE EVA from DEC 00:17:A4 MSL Tape
Definition at line 36 of file HPVirtualServerDescription.java.
Constructor & Destructor Documentation
HPVirtualServerDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 39 of file HPVirtualServerDescription.java.
Referenced by HPVirtualServerDescription.getDesc().
HPVirtualServerDescription (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 74 of file HPVirtualServerDescription.java.
Member Function Documentation
String descPort () [inline]
describe the WWPN's unique port label/index
Returns
the unique name for the port WWPN
Definition at line 107 of file HPVirtualServerDescription.java.
References WWNDesc.wwn.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong used to restrict matching to strong-matches only. This is a weak-confidence description, so will return null for strong-only matching
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 52 of file HPVirtualServerDescription.java.
References DevRole.max.
Referenced by WWNDescription.getWWNDescriptor().
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong used to restrict matching to strong-matches only. This is a weak-confidence description, so will return null for strong-only matching
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 60 of file HPVirtualServerDescription.java.
References HPVirtualServerDescription.HPVirtualServerDescription(), and WWNDesc.WWNDescInitiator.isA().
String toString () [inline]
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
See also
getDesc(boolean,boolean,String)
Returns
generated alias or nickname for the WWN
Definition at line 85 of file HPVirtualServerDescription.java.
References WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/HPVirtualServerDescription.java