HPDotHillDescription Class Reference
HPDotHillDescription (ie P2000-123456-B1) breaks out a unique code and the port information from the WWPN of a Dot Hill Systems Modular Smart Array P2000 which HP resells.
Public Member Functions
HPDotHillDescription (String wwn)
create an instance with brief set to false.
String toString ()
return a description or alias for this WWN
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
HPDotHillDescription (ie P2000-123456-B1) breaks out a unique code and the port information from the WWPN of a Dot Hill Systems Modular Smart Array P2000 which HP resells.
These descriptors are fairly weak: I'm somewhat sure of the serial, but only two matches for the port-number logic.
Definition at line 15 of file HPDotHillDescription.java.
Constructor & Destructor Documentation
HPDotHillDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 18 of file HPDotHillDescription.java.
Referenced by HPDotHillDescription.getDesc().
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is ignored: this class has only one representation of the WWN description or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 31 of file HPDotHillDescription.java.
References DevRole.max.
Referenced by WWNDescription.getWWNDescriptor().
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is ignored: this class has only one representation of the WWN description or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 39 of file HPDotHillDescription.java.
References HPDotHillDescription.HPDotHillDescription(), and WWNDesc.WWNDescTarget.isA().
String toString () [inline]
return a description or alias for this WWN
Returns
generated alias or nickname for the WWN
Definition at line 54 of file HPDotHillDescription.java.
References WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/HPDotHillDescription.java