EMCClariionDescription Class Reference
EMCClariionDescription (ie CL-01234567-SPB1) describes the serial and CL of a Clariion; EMC doesn't seem to include any additional data in the WWPN.
Public Member Functions
EMCClariionDescription (String wwn)
create an instance with brief set to false.
String toString ()
return a description or alias for this WWN
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
EMCClariionDescription (ie CL-01234567-SPB1) describes the serial and CL of a Clariion; EMC doesn't seem to include any additional data in the WWPN.
See also
EMCSymmetrixDescription
EMCVMAXDescription
EMCVPLEXDescription
Definition at line 13 of file EMCClariionDescription.java.
Constructor & Destructor Documentation
EMCClariionDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 16 of file EMCClariionDescription.java.
Referenced by EMCClariionDescription.getDesc().
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is ignored: this class has only one representation of the WWN description or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 29 of file EMCClariionDescription.java.
References DevRole.max.
Referenced by WWNDescription.getWWNDescriptor().
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is ignored: this class has only one representation of the WWN description or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 37 of file EMCClariionDescription.java.
References EMCClariionDescription.EMCClariionDescription(), and WWNDesc.WWNDescTarget.isA().
String toString () [inline]
return a description or alias for this WWN
Returns
generated alias or nickname for the WWN
Definition at line 52 of file EMCClariionDescription.java.
References WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/EMCClariionDescription.java