AIXLPARServerDescription Class Reference
AIXLPARServerDescription (ie LPAR-012345:0) breaks out the uniqueness number and port index from the WWPN.
Public Member Functions
AIXLPARServerDescription (String wwn)
create an instance with brief set to false.
AIXLPARServerDescription (boolean brief, String wwn)
create an instance with the given WWN.
String descPort ()
describe the WWPN's unique port label/index
String toString ()
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
AIXLPARServerDescription (ie LPAR-012345:0) breaks out the uniqueness number and port index from the WWPN.
There may be difficulty here in determining whether a device is a switch or a NPIV bladecenter for servers; it's not obvious from the WWPNs
Definition at line 9 of file AIXLPARServerDescription.java.
Constructor & Destructor Documentation
AIXLPARServerDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 12 of file AIXLPARServerDescription.java.
Referenced by AIXLPARServerDescription.getDesc().
AIXLPARServerDescription (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 46 of file AIXLPARServerDescription.java.
Member Function Documentation
String descPort () [inline]
describe the WWPN's unique port label/index
Returns
the unique name for the port WWPN
Definition at line 79 of file AIXLPARServerDescription.java.
References WWNDesc.wwn.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong used to restrict matching to strong-matches only. This is a weak-confidence description, so will return null for strong-only matching
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 25 of file AIXLPARServerDescription.java.
References DevRole.max.
Referenced by WWNDescription.getWWNDescriptor().
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong used to restrict matching to strong-matches only. This is a weak-confidence description, so will return null for strong-only matching
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 33 of file AIXLPARServerDescription.java.
References AIXLPARServerDescription.AIXLPARServerDescription(), and WWNDesc.WWNDescInitiator.isA().
String toString () [inline]
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
See also
getDesc(boolean,boolean,String)
Returns
generated alias or nickname for the WWN
Definition at line 57 of file AIXLPARServerDescription.java.
References WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/AIXLPARServerDescription.java