IBMSVCDescription Class Reference
IBMSVCDescription (ie SVCe0_Node0E_Port1) breaks out the SVC number, node, and port of a WWPN; it does not see where two nodes of a SVC are related.
Public Member Functions
IBMSVCDescription (String wwn)
create an instance with brief set to false.
IBMSVCDescription (boolean brief, String wwn)
create an instance with the given WWN.
String toString ()
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
IBMSVCDescription (ie SVCe0_Node0E_Port1) breaks out the SVC number, node, and port of a WWPN; it does not see where two nodes of a SVC are related.
Definition at line 13 of file IBMSVCDescription.java.
Constructor & Destructor Documentation
IBMSVCDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 16 of file IBMSVCDescription.java.
Referenced by IBMSVCDescription.getDesc().
IBMSVCDescription (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 21 of file IBMSVCDescription.java.
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is used to show only those patterns we're 100% certain about: this class is a strong representation of 505076801*, but a weak representation of all 50507680* (notice that the last nibble is fuzzy, meaning we could get duplicate names)
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 34 of file IBMSVCDescription.java.
References DevRole.max.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is used to show only those patterns we're 100% certain about: this class is a strong representation of 505076801*, but a weak representation of all 50507680* (notice that the last nibble is fuzzy, meaning we could get duplicate names)
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 42 of file IBMSVCDescription.java.
References IBMSVCDescription.IBMSVCDescription(), and WWNDesc.WWNDescTarget.isA().
String toString () [inline]
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
See also
getDesc(boolean,boolean,String)
Returns
generated alias or nickname for the WWN
Definition at line 61 of file IBMSVCDescription.java.
References WWNDesc.brief, and WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/IBMSVCDescription.java