SymbiosDescription Class Reference
SymbiosDescription (ie DS3400-123456:A:FC1) breaks out the UUID, Controller, and FC port for a DS3400 storage array ref: IBM Storage Systems WWPN Determination.
Public Member Functions
SymbiosDescription (String wwn)
create an instance with brief set to false.
SymbiosDescription (boolean brief, String wwn)
create an instance with the given WWN.
String toString ()
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
SymbiosDescription (ie DS3400-123456:A:FC1) breaks out the UUID, Controller, and FC port for a DS3400 storage array ref: IBM Storage Systems WWPN Determination.
Definition at line 15 of file SymbiosDescription.java.
Constructor & Destructor Documentation
SymbiosDescription (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 18 of file SymbiosDescription.java.
Referenced by SymbiosDescription.getDesc().
SymbiosDescription (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 23 of file SymbiosDescription.java.
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 36 of file SymbiosDescription.java.
References DevRole.max.
Referenced by WWNDescription.getWWNDescriptor().
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is used to ask for a shorter description: a more concise nickname or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 44 of file SymbiosDescription.java.
References WWNDesc.WWNDescTarget.isA(), and SymbiosDescription.SymbiosDescription().
String toString () [inline]
return a description or alias for this WWN; if brief is set to true during the call to getDesc(), then a shorter description or alias will be returned
See also
getDesc(boolean,boolean,String)
Returns
generated alias or nickname for the WWN
Definition at line 61 of file SymbiosDescription.java.
References WWNDesc.brief, and WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/SymbiosDescription.java