IBM500507630Description Class Reference
IBM500507630 covers the following types:
Public Member Functions
IBM500507630Description (String wwn)
create an instance with brief set to false.
IBM500507630Description (boolean brief, String wwn)
create an instance with the given WWN.
String toString ()
return a description or alias for this WWN
Static Public Member Functions
static WWNDesc getDesc (boolean strong, boolean brief, String wwn)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role)
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Additional Inherited Members
Detailed Description
IBM500507630 covers the following types:
1750 DS6000 500507630zFExxxx 500507630zyyxxxx
2105 ESS or Shark 5005076300c0xxxx 5005076300yyxxxx
2107 DS8000 500507630zFFxxxx 500507630zyyyxxx
See also
http://aussiestorageblog.files.wordpress.com/2013/01/ibm-storage-systems-wwpn-determination-version-6-6.pdf
http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/TD105450
http://linuxvm.org/present/SHARE100/S9333NFa.pdf seems to imply that 50050763004029a0 is actually a tape ID within a IBM 3590(E) tape library
Definition at line 22 of file IBM500507630Description.java.
Constructor & Destructor Documentation
IBM500507630Description (String wwn) [inline]
create an instance with brief set to false.
This is a convenience function to support the older constructor model
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
wwn the WWN to evaluate and describe
Definition at line 25 of file IBM500507630Description.java.
Referenced by IBM500507630Description.getDesc().
IBM500507630Description (boolean brief, String wwn) [inline]
create an instance with the given WWN.
Values given to the constructor are simply copied to internal variables for later use
Exceptions
java.lang.NullPointerException if the given wwn is null
Parameters
brief whether an abbreviated description is requested
wwn the WWN to evaluate and describe
Definition at line 30 of file IBM500507630Description.java.
Member Function Documentation
static WWNDesc getDesc (boolean strong, boolean brief, String wwn) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is ignored: this class has only one representation of the WWN description or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
Definition at line 43 of file IBM500507630Description.java.
References DevRole.max.
static WWNDesc getDesc (boolean strong, boolean brief, String wwn, int role) [inline], [static]
If this class matches or describes the given WWN, returns a new instance of this class loaded with the given WWN.
Returns
new instance of this class, or null if the given wwn does not match this class
Parameters
strong is ignored: this class is a strong representation, not a weak one based on empirical matching, hence can always be used with confidence
brief is ignored: this class has only one representation of the WWN description or alias
wwn the WWN (WWPN or WWNN, but typically WWPN) to match
role Role (Initiator/Switch/Target) to check for
Definition at line 51 of file IBM500507630Description.java.
References IBM500507630Description.IBM500507630Description(), and WWNDesc.WWNDescTarget.isA().
String toString () [inline]
return a description or alias for this WWN
Returns
generated alias or nickname for the WWN
Definition at line 66 of file IBM500507630Description.java.
References WWNDesc.wwn.
The documentation for this class was generated from the following file:
java/IBM500507630Description.java